version: "2"
services:
    web:
        container_name: esgi-web-2
        image: nginx:latest
        ports:
            - "9290:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
            - database
    php:
        container_name: esgi-php-2
        build: php-fpm
        volumes:
            - ./code:/code
    database:
        container_name: esgi-db-2
        image: mysql:5.5
        ports:
            - "9291:3306"  
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=esgi
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
    phpmyadmin:
      container_name: esgi-pma-2
      image: phpmyadmin/phpmyadmin
      restart: always
      links:
        - database
      ports:
        - 9292:80
      environment:
        PMA_HOST: esgi-db
        PMA_USER: root
        PMA_PASSWORD: root
        PMA_ARBITRARY: 1
